#          .
#       ":"
#     ___:____     |"\/"|
#   ,'        `.    \  /
#   |  O        \___/  |
# ~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^

#Load libraries
library(pacman)
pacman::p_load(data.table, ggplot2, lubridate, stringr, ggpubr, dplyr, cowplot)

# Specify a main folder
MAIN <- "~/Documents/Github/master_thesis/ELISA"

# Make folder with desired Plates to be analysed. Plate names should be formatted as: Plate_1_20220623 (Plate_X_YYYYMMDD)
Input_Directory <- file.path(MAIN, "ALL/")

# Specify where to store the Standard curve plots generated by the Elisa_Fx() function
Output_Directory <- file.path(Input_Directory, "Output")

# Specify where you would like to store the other figures generated by this script
save_to = "~/Documents/Github/master_thesis/thesis_figs"

# What cell lines are you using as your positive/negative controls?
POSITIVE_CTRL = "MyD88-GFP"
NEGATIVE_CTRL = "204_TRIPLE_KO"

# Source the functions needed to run this script
ifelse(test = file.exists("https://raw.githubusercontent.com/tlobnow/master_thesis/main/scripts/functions.R"), 
       yes  = source("https://raw.githubusercontent.com/tlobnow/master_thesis/main/scripts/functions.R"), 
       no   = source("~/Documents/Github/master_thesis/scripts/functions.R"))

# What are the names of the csv files in each plate folder?
CELL_LINES    <- "CELL_LINES.csv"       # COHORT
STIM_DAYS     <- "STIMULATION_DAYS.csv" # SAMPLE_DAY
CONDITIONS    <- "CONDITIONS.csv"       # STIMULATION_CONDITION
MEASUREMENTS  <- "MEASUREMENTS.csv"     # VALUES_MEASURED

# Specify the Dilution factor used for the samples
### will be revised as an extra csv file! <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
DILUTION_FACTOR_2  <- 2
DILUTION_FACTOR_5  <- 5
DILUTION_FACTOR_10 <- 10

# POINT 1: Calculate the Standard Curve means
# POINT 2: Plot the Standard curve and fit a linear trend line -> We use the equation to estimate IL-2 conc. of our unknown samples
# Run ELISA_Fx() to generate standard curves and calculate the IL-2 concentrations
All_plates_data <- ELISA_Fx(Input_Directory, Output_Directory)
# IL2_concentration is the raw concentration extrapolated from the linear regression model (based on the standard curve)
# IL2_concentration_DILUTION_FACTOR is the adjusted IL-2 concentration (with regard to the dilutions used)

# Prep Analysis by renaming cell lines as needed
### will be revised as an extra csv file! <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
All_plates_data$CELL_LINES <- gsub("_H$|_E$", "", All_plates_data$CELL_LINES)
All_plates_data$CELL_LINES <- ifelse(grepl("^BDLD_", All_plates_data$CELL_LINES), paste0("MyD88-", All_plates_data$CELL_LINES, "-T6BM"), All_plates_data$CELL_LINES)
All_plates_data <- All_plates_data %>% 
  mutate(CELL_LINES = case_when(CELL_LINES == "MyD88-BDLD_10-T6BM"  ~ "MyD88-CNTRL-T6BM",
                                CELL_LINES == "3E10_GFP"  ~ "MyD88-GFP",
                                CELL_LINES == "69"  ~ "WT_EL4",
                                CELL_LINES == "614" ~ "DHF91_H",
                                CELL_LINES == "614_L" ~ "DHF91_L",
                                CELL_LINES == "590" ~ "MyD88-T6BM_H",
                                CELL_LINES == "590_L" ~ "MyD88-T6BM",
                                CELL_LINES == "591_L" ~ "MyD88-T6BM-3xAla",
                                CELL_LINES == "631" ~ "MyD88-TIR-T6BM-3xAla",
                                CELL_LINES == "632" ~ "DHF91-T6BM-3xAla",
                                CELL_LINES != "614" ~ CELL_LINES))

# POINT 3: Set negative values to 0 (we )
# We cannot really measure negative fluorescence values - this is unrealistic.
All_plates_data <- All_plates_data %>%
  mutate(MEASUREMENTS      = case_when(MEASUREMENTS < 0 ~ 0, TRUE ~ MEASUREMENTS),
         IL2_concentration = case_when(IL2_concentration < 0 ~ 0, TRUE ~ IL2_concentration),
         IL2_concentration_DILUTION_FACTOR = case_when(IL2_concentration_DILUTION_FACTOR < 0 ~ 0, TRUE ~ IL2_concentration_DILUTION_FACTOR),
         CONTROL_CELL_LINE = case_when(CELL_LINES  %in% c("WT_EL4", "MyD88-GFP", "204_TRIPLE_KO") ~ T,
                                       !CELL_LINES %in% c("WT_EL4", "MyD88-GFP", "204_TRIPLE_KO") ~ F))

# Adjust the column types as needed
# we want to turn stimulation conditions and stimulation days into factors for easier handling downstream
All_plates_data$CONDITIONS <- as.factor(All_plates_data$CONDITIONS)
All_plates_data$STIM_DAYS  <- as.factor(All_plates_data$STIM_DAYS)

# I am providing an example cohort contained in my All_plates_data data frame to test the functions:
COHORT = "MyD88-BDLD_57-T6BM"
COLOR = "salmon"
SEED = 600

plot4COHORT <- function(COHORT, COLOR = "salmon", SEED = 600, plot_pval = T, run_anova = F,
                        POSITIVE_CTRL, NEGATIVE_CTRL) {

  # Set the plotting colors
  fill_colors <- c("UNSTIM" = "gray50")
  fill_colors["STIM"]   <- COLOR
  
  # Data Filtering
  # Step 1: Data Filtering and Control Computation
  # Unique dates corresponding to the given cohort.
  COHORT_DATES <- All_plates_data %>% filter(CELL_LINES == COHORT) %>% distinct(Date) %>% pull(Date)
  # Unique plate names corresponding to the given cohort.
  COHORT_PLATES <- All_plates_data %>% filter(CELL_LINES == COHORT) %>% distinct(Plate) %>% pull(Plate)
  # Unique stim days corresponding to the given cohort.
  STIM_DAYS_COHORT <- All_plates_data[All_plates_data$CELL_LINES %in% COHORT, ] %>% pull(STIM_DAYS) %>% unique()
  
  # Subset the dataset.
  COHORT_SUBSET <- All_plates_data %>%
    filter(Date %in% COHORT_DATES,
           Plate %in% COHORT_PLATES,
           STIM_DAYS %in% STIM_DAYS_COHORT,
           CELL_LINES %in% c(POSITIVE_CTRL,
                             NEGATIVE_CTRL,
                             COHORT))
  
  # POINT 4: Prepare the normalization by calculating the mean of the unstimulated, negative control per stimulation day
  baseline <- COHORT_SUBSET %>%
    group_by(Date, STIM_DAYS) %>%
    filter(CELL_LINES == NEGATIVE_CTRL, CONDITIONS == "UNSTIM") %>% 
    summarise(baseline_control_value = mean(IL2_concentration_DILUTION_FACTOR))
  # join the calculated values with the cohort subset df
  COHORT_SUBSET <- left_join(COHORT_SUBSET, baseline) %>%
    mutate(IL2_concentration_DILUTION_FACTOR_REDUCED = IL2_concentration_DILUTION_FACTOR - baseline_control_value)
  
  # II. Prepare the normalization by calculating the mean of the stimulated, positive control per stimulation day
  control_mean_per_day <- COHORT_SUBSET %>%
    filter(CELL_LINES == POSITIVE_CTRL, CONDITIONS == "STIM") %>%
    group_by(Date, STIM_DAYS) %>%
    summarise(control_mean_measurements = mean(IL2_concentration_DILUTION_FACTOR_REDUCED))
  COHORT_SUBSET <- left_join(COHORT_SUBSET, control_mean_per_day, by = c("Date", "STIM_DAYS"))
  
  # III. Perform the normalization of your sample IL2_concentration_DILUTION_FACTOR measurements
  COHORT_SUBSET_NORMALIZED <- COHORT_SUBSET %>%
    group_by(Date, Plate, STIM_DAYS, CELL_LINES, 
             CONDITIONS
             ) %>%
    mutate(IL2_concentration_DILUTION_FACTOR_NORMALIZED = case_when(IL2_concentration_DILUTION_FACTOR_REDUCED/control_mean_measurements < 0 ~ 0, TRUE ~ IL2_concentration_DILUTION_FACTOR_REDUCED/control_mean_measurements),
           triplicate_mean_per_day = mean(IL2_concentration_DILUTION_FACTOR_NORMALIZED)) %>%
    ungroup()
  
  # Calculate the mean of means (MOM)
  MEANS <- COHORT_SUBSET_NORMALIZED %>%
    group_by(CELL_LINES, CONDITIONS) %>%
    distinct(triplicate_mean_per_day, STIM_DAYS, .keep_all = T) %>%
    ungroup()
  
  # Calculate the mean of means of means (Super MOM) for the error bars
  MOM_SUBSET <- MEANS %>%
    group_by(CELL_LINES, CONDITIONS, Date) %>%
    summarise(triplicate_sd_per_day = sd(triplicate_mean_per_day),
              triplicate_mean_per_day = mean(triplicate_mean_per_day)) %>%
    distinct(.keep_all = T)
  
  # Pairwise t-test
  pairwise_ttest <- function(data, return_annotation = FALSE) {
    p_values <- pairwise.t.test(data$triplicate_mean_per_day, data$CONDITIONS, p.adjust.method = "none")$p.value
    
    if (return_annotation) {
      p_annotation <- ifelse(p_values < 0.001, '***', 
                             ifelse(p_values < 0.01, '**', 
                                    ifelse(p_values < 0.05, '*', 
                                           'ns')))
      return(p_annotation)
    } else {
      return(formatC(p_values, format = "e", digits = 3))
    }
  }
      
  # calculate statistical significance using a t-test for each cell line (df of interest is split into groups based on cell lines)
  annotations <- sapply(split(MEANS, MEANS$CELL_LINES), pairwise_ttest)
  p_val       <- sapply(split(MEANS, MEANS$CELL_LINES), function(data) pairwise_ttest(data, return_annotation = TRUE))
      
  # Plot without statistics (Anova/t-test)
  plot <- ggplot(MEANS, aes(x = CELL_LINES)) +
    geom_col(     data = MOM_SUBSET, aes(y = triplicate_mean_per_day, fill = CONDITIONS), position = position_dodge(width = 1), alpha = 0.5) +
    geom_point(   data = MEANS,       aes(y = triplicate_mean_per_day, group = CONDITIONS, shape = STIM_DAYS), position = position_jitterdodge(jitter.height = 0, jitter.width = 1.2, seed = SEED), col = "white", size = 4) +
    geom_point(   data = MEANS,       aes(y = triplicate_mean_per_day, group = CONDITIONS, shape = STIM_DAYS), position = position_jitterdodge(jitter.height = 0, jitter.width = 1.2, seed = SEED), col = "black", size = 3) +
    geom_errorbar(data = MOM_SUBSET, aes(ymin = triplicate_mean_per_day - triplicate_sd_per_day, 
                                               ymax = triplicate_mean_per_day + triplicate_sd_per_day, group = CONDITIONS), width = 0.25, position = position_dodge(width = 1)) +
    theme_cowplot() +
    theme(legend.position = "bottom") +
    labs(x = "",
         y = "relative IL-2 conc.") +
    scale_fill_manual(values = fill_colors) +
    ggtitle(paste(COHORT, "ELISA")) +
    theme(plot.title = element_text(hjust = 0.5))
  
  if (plot_pval) {
    plot <- plot +
      geom_text(data = data.frame(CELL_LINES = names(annotations), y = max(MEANS$triplicate_mean_per_day) + 0.1, label = annotations), aes(y = y, label = label), col = "gray40", size = 4) +
      geom_text(data = data.frame(CELL_LINES = names(p_val), y = max(MEANS$triplicate_mean_per_day) + 0.2, label = p_val), aes(y = y, label = label), size = 7)
  }
  
  # plot
  
  if (run_anova) {
    # Anova Matrix
    # Pull out the cohort order list
    Cohort_Order_Table <- COHORT_SUBSET %>% pull(CELL_LINES) %>% as.data.table() %>% unique()
    
    # rename the column to Cohort
    colnames(Cohort_Order_Table) <- c("CELL_LINES")
    
    # add a row number column
    Cohort_Order_Table <- Cohort_Order_Table %>% mutate(ORDER_NUMBER = row_number())
    
    #Create matrix using Cohort list as row and columns
    Statistics_matrix <- matrix(data = NA, nrow = nrow(Cohort_Order_Table)+1, ncol = nrow(Cohort_Order_Table)+1)
    for(col_index in 1:nrow(Cohort_Order_Table)){
      Statistics_matrix[1, col_index+1] = Cohort_Order_Table$CELL_LINES[col_index]
    }
    
    for(row_index in 1:nrow(Cohort_Order_Table)){
      Statistics_matrix[row_index+1, 1] = Cohort_Order_Table$CELL_LINES[row_index]
    }
    
    # Do statistical tests to fill up matrix
    for(col_index in 2:ncol(Statistics_matrix)){
      for(row_index in 2:nrow(Statistics_matrix)){
        if(row_index != col_index){
          MOM_SUBSET_temp <- MOM_SUBSET %>% filter(CELL_LINES == Statistics_matrix[1, col_index] | CELL_LINES == Statistics_matrix[row_index, 1])
          Stat <- 1
          Stat <- aov(triplicate_mean_per_day ~ CELL_LINES, data = MOM_SUBSET_temp)
          Stat <- summary(Stat)
          Stat <- Stat[[1]]$`Pr(>F)`[1]
          Stat <- signif(Stat, digits = 5)
          Statistics_matrix[row_index, col_index] = as.numeric(Stat)
        } else {
          Statistics_matrix[row_index, col_index] = 1
        }
      }
    }
    
    Statistics_Save <- file.path(paste0(save_to, paste0("/",COHORT,".csv")))
    fwrite(Statistics_matrix, Statistics_Save, row.names = FALSE, col.names = F)
  }
  
  ggsave(filename = paste0(save_to, paste0("/",COHORT,"_ELISA.svg")), 
         plot = plot, device = "svg", width = 6, height = 4)
  
  return(plot)
  
}

plot4COHORT(COHORT = paste0("MyD88-","BDLD_6","-T6BM"), COLOR = "#2d8659", SEED = 600, run_anova = T,
            POSITIVE_CTRL = POSITIVE_CTRL, NEGATIVE_CTRL = NEGATIVE_CTRL)

plot4DAY <- function(DAY, COLOR = "salmon", SEED = 600, plot_pval = T, run_anova = F,
                     POSITIVE_CTRL, NEGATIVE_CTRL) {
  # PLOTTING COLORS
  fill_colors <- c("UNSTIM" = "gray40")
  fill_colors["STIM"]   <- COLOR
  
  # Step 1: Data Filtering and Control Computation
  # Unique dates corresponding to the given cohort.
  COHORT_DATES <- All_plates_data %>% filter(Date == DAY) %>% distinct(Date) %>% pull(Date)
  # Unique cohorts corresponding to the given date
  COHORTS <- All_plates_data %>% filter(Date == DAY) %>% distinct(CELL_LINES) %>% pull(CELL_LINES)
  # Unique plate names corresponding to the given date
  COHORT_PLATES <- All_plates_data %>% filter(Date == DAY) %>% distinct(Plate) %>% pull(Plate)
  # Unique stim days corresponding to the given date
  STIM_DAYS_COHORT <- All_plates_data[All_plates_data$Date %in% as.IDate(DAY), ] %>% pull(STIM_DAYS) %>% unique()
  
  # Subset the dataset.
  COHORT_SUBSET <- All_plates_data %>%
    filter(Date %in% COHORT_DATES,
           Plate %in% COHORT_PLATES,
           STIM_DAYS %in% STIM_DAYS_COHORT,
           CELL_LINES %in% c(POSITIVE_CTRL,
                             NEGATIVE_CTRL,
                             COHORTS))
  
  # POINT 4: Prepare the normalization by calculating the mean of the unstimulated, negative control per stimulation day
  baseline <- COHORT_SUBSET %>%
    group_by(Date, STIM_DAYS, Plate) %>%
    filter(CELL_LINES == NEGATIVE_CTRL, CONDITIONS == "UNSTIM") %>% 
    summarise(baseline_control_value = mean(IL2_concentration_DILUTION_FACTOR))
  # join the calculated values with the cohort subset df
  COHORT_SUBSET <- left_join(COHORT_SUBSET, baseline) %>%
    mutate(IL2_concentration_DILUTION_FACTOR_REDUCED = case_when(!is.na(baseline_control_value) ~ IL2_concentration_DILUTION_FACTOR - baseline_control_value,
                     TRUE ~ IL2_concentration_DILUTION_FACTOR))
  
  # II. Prepare the normalization by calculating the mean of the stimulated, positive control per stimulation day
  control_mean_per_day <- COHORT_SUBSET %>%
    filter(CELL_LINES == POSITIVE_CTRL, CONDITIONS == "STIM") %>%
    group_by(Date, STIM_DAYS, Plate) %>%
    summarise(control_mean_measurements = mean(IL2_concentration_DILUTION_FACTOR_REDUCED))
  COHORT_SUBSET <- left_join(COHORT_SUBSET, control_mean_per_day, by = c("Date", "STIM_DAYS", "Plate"))
  
  # III. Perform the normalization of your sample IL2_concentration_DILUTION_FACTOR measurements
  COHORT_SUBSET_NORMALIZED <- COHORT_SUBSET %>%
    group_by(Date, Plate, STIM_DAYS, CELL_LINES, 
             CONDITIONS
    ) %>%
    mutate(IL2_concentration_DILUTION_FACTOR_NORMALIZED = case_when(IL2_concentration_DILUTION_FACTOR_REDUCED/control_mean_measurements < 0 ~ 0, TRUE ~ IL2_concentration_DILUTION_FACTOR_REDUCED/control_mean_measurements),
           triplicate_mean_per_day = mean(IL2_concentration_DILUTION_FACTOR_NORMALIZED)) %>%
    ungroup()
  
  # Calculate the mean of means (MOM)
  MEANS <- COHORT_SUBSET_NORMALIZED %>%
    group_by(CELL_LINES, CONDITIONS) %>%
    distinct(triplicate_mean_per_day, STIM_DAYS, .keep_all = T) %>%
    ungroup()
  
  # Calculate the mean of means of means (Super MOM) for the error bars
  MOM_SUBSET <- MEANS %>%
    group_by(CELL_LINES, CONDITIONS, Date, #Plate
             ) %>%
    summarise(triplicate_sd_per_day = sd(triplicate_mean_per_day),
              triplicate_mean_per_day = mean(triplicate_mean_per_day)) %>%
    distinct(.keep_all = T)
  
  # Pairwise t-test
  pairwise_ttest <- function(data, return_annotation = FALSE) {
    p_values <- pairwise.t.test(data$triplicate_mean_per_day, data$CONDITIONS, p.adjust.method = "none")$p.value
    
    if (return_annotation) {
      p_annotation <- ifelse(p_values < 0.001, '***', 
                             ifelse(p_values < 0.01, '**', 
                                    ifelse(p_values < 0.05, '*', 
                                           'ns')))
      return(p_annotation)
    } else {
      return(formatC(p_values, format = "e", digits = 3))
    }
  }
  
  # calculate statistical significance using a t-test for each cell line (df of interest is split into groups based on cell lines)
  annotations <- sapply(split(MEANS, MEANS$CELL_LINES), pairwise_ttest)
  p_val       <- sapply(split(MEANS, MEANS$CELL_LINES), function(data) pairwise_ttest(data, return_annotation = TRUE))
  
  # Plot without statistics (Anova/t-test)
  plot <- ggplot(MEANS, aes(x = CELL_LINES)) +
    geom_col(     data = MOM_SUBSET, aes(y = triplicate_mean_per_day, fill = CONDITIONS), position = position_dodge(width = 1), alpha = 0.5) +
    geom_point(   data = MEANS,       aes(y = triplicate_mean_per_day, group = CONDITIONS, shape = STIM_DAYS), position = position_jitterdodge(jitter.height = 0, jitter.width = 1.2, seed = SEED), col = "white", size = 4) +
    geom_point(   data = MEANS,       aes(y = triplicate_mean_per_day, group = CONDITIONS, shape = STIM_DAYS), position = position_jitterdodge(jitter.height = 0, jitter.width = 1.2, seed = SEED), col = "black", size = 3) +
    geom_errorbar(data = MOM_SUBSET, aes(ymin = triplicate_mean_per_day - triplicate_sd_per_day, 
                                         ymax = triplicate_mean_per_day + triplicate_sd_per_day, group = CONDITIONS), width = 0.25, position = position_dodge(width = 1)) +
    theme_cowplot() +
    theme(legend.position = "bottom") +
    labs(x = "",
         y = "relative IL-2 conc.") +
    scale_fill_manual(values = fill_colors) +
    ggtitle(paste(DAY, "ELISA")) +
    theme(plot.title = element_text(hjust = 0.5))
  
  if (plot_pval) {
    plot <- plot +
      geom_text(data = data.frame(CELL_LINES = names(annotations), y = max(MEANS$triplicate_mean_per_day) + 0.1, label = annotations), aes(y = y, label = label), col = "gray40", size = 4) +
      geom_text(data = data.frame(CELL_LINES = names(p_val), y = max(MEANS$triplicate_mean_per_day) + 0.2, label = p_val), aes(y = y, label = label), size = 7)
  }
  
  ggsave(filename = paste0(save_to, paste0("/",DAY,"_ELISA.svg")), 
         plot = plot, device = "svg", width = 24, height = 16)
  plot
  
  if (run_anova) {
    # Anova Matrix
    # Pull out the cohort order list
    Cohort_Order_Table <- COHORT_SUBSET %>% pull(CELL_LINES) %>% as.data.table() %>% unique()
    
    # rename the column to Cohort
    colnames(Cohort_Order_Table) <- c("CELL_LINES")
    
    # add a row number column
    Cohort_Order_Table <- Cohort_Order_Table %>% mutate(ORDER_NUMBER = row_number())
    
    #Create matrix using Cohort list as row and columns
    Statistics_matrix <- matrix(data = NA, nrow = nrow(Cohort_Order_Table)+1, ncol = nrow(Cohort_Order_Table)+1)
    for(col_index in 1:nrow(Cohort_Order_Table)){
      Statistics_matrix[1, col_index+1] = Cohort_Order_Table$CELL_LINES[col_index]
    }
    
    for(row_index in 1:nrow(Cohort_Order_Table)){
      Statistics_matrix[row_index+1, 1] = Cohort_Order_Table$CELL_LINES[row_index]
    }
    
    # Do statistical tests to fill up matrix
    for(col_index in 2:ncol(Statistics_matrix)){
      for(row_index in 2:nrow(Statistics_matrix)){
        if(row_index != col_index){
          MOM_SUBSET_temp <- MOM_SUBSET %>% filter(CELL_LINES == Statistics_matrix[1, col_index] | CELL_LINES == Statistics_matrix[row_index, 1])
          Stat <- 1
          Stat <- aov(triplicate_mean_per_day ~ CELL_LINES, data = MOM_SUBSET_temp)
          Stat <- summary(Stat)
          Stat <- Stat[[1]]$`Pr(>F)`[1]
          Stat <- signif(Stat, digits = 5)
          Statistics_matrix[row_index, col_index] = as.numeric(Stat)
        } else {
          Statistics_matrix[row_index, col_index] = 1
        }
      }
    }
    
    Statistics_Save <- file.path(paste0(save_to, paste0("/",DAY,".csv")))
    fwrite(Statistics_matrix, Statistics_Save, row.names = FALSE, col.names = F)
  }
  
  return(plot)
}

plot4DAY(DAY = "2023-05-04", COLOR = "salmon", SEED = 600, plot_pval = T, run_anova = F, POSITIVE_CTRL = "WT_EL4",    NEGATIVE_CTRL = "204_TRIPLE_KO")
plot4DAY(DAY = "2023-07-04", COLOR = "salmon", SEED = 600, plot_pval = T, run_anova = T, POSITIVE_CTRL = "MyD88-GFP", NEGATIVE_CTRL = "204_TRIPLE_KO")
plot4DAY(DAY = "2023-05-12", COLOR = "salmon", SEED = 600, plot_pval = T, run_anova = F, POSITIVE_CTRL = "MyD88-GFP", NEGATIVE_CTRL = "204_TRIPLE_KO")
plot4DAY(DAY = "2022-06-23", COLOR = "salmon", SEED = 600, plot_pval = T, run_anova = F, POSITIVE_CTRL = "WT_EL4",    NEGATIVE_CTRL = "204_TRIPLE_KO")

