#          .
#       ":"
#     ___:____     |"\/"|
#   ,'        `.    \  /
#   |  O        \___/  |
# ~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^

#Load libraries
library(pacman)
pacman::p_load(data.table, ggplot2, lubridate, stringr, ggpubr, dplyr, cowplot)

MAIN <- "/Volumes/TAYLOR-LAB/Finn/ELISA"    # Specify a main folder
Input_Directory <- file.path(MAIN, "ALL/")  # Make folder with desired Plates to be analysed. Plate names should be formatted as: Plate_1_20220623 (Plate_X_YYYYMMDD)
Output_Directory <- file.path(Input_Directory, "Output")  # Specify where to store the Standard curve plots generated by the Elisa_Fx() function
save_to = ifelse(test = dir.exists("/Volumes/TAYLOR-LAB/Finn/ELISA/figures"), # Specify where you would like to store the other figures generated by this script
                 yes = "/Volumes/TAYLOR-LAB/Finn/ELISA/figures",
                 no = "~/Desktop/ELISA_Plots/")   

source(file = ifelse(exists("https://raw.githubusercontent.com/tlobnow/coding_universe/main/scripts/functions.R"), 
                     yes =  "https://raw.githubusercontent.com/tlobnow/coding_universe/main/scripts/functions.R",
                     no  =  "~/Documents/Github/coding_universe/scripts/functions.R"))

# What are the names of the csv files in each plate folder?
CELL_LINES    <- "CELL_LINES.csv"       # COHORT
STIM_DAYS     <- "STIMULATION_DAYS.csv" # SAMPLE_DAY
CONDITIONS    <- "CONDITIONS.csv"       # STIMULATION_CONDITION
MEASUREMENTS  <- "MEASUREMENTS.csv"     # VALUES_MEASURED
DILUTIONS     <- "DILUTIONS.csv"        # new addition that multiplied
NAME_KEY      <- fread(paste0(Input_Directory, "ELISA_CL_KEY.csv"))

# POINT 1: Calculate the Standard Curve means
# POINT 2: Plot the Standard curve and fit a linear trend line -> We use the equation to estimate IL-2 conc. of our unknown samples
# Run ELISA_Fx() to generate standard curves and calculate the IL-2 concentrations
# Concentration is the raw concentration extrapolated from the linear regression model (based on the standard curve)
# Concentration_DILUTION_FACTOR is the adjusted IL-2 concentration (with regard to the DILUTION used)
All_plates_data_raw <- ELISA_Fx(Input_Directory, Output_Directory)
All_plates_data <- left_join(All_plates_data_raw, NAME_KEY)

# Ensure that partially filled data is excluded (sometimes the tables are not filled consistently --> will be ignored/filtered out for now.)
All_plates_data <- All_plates_data %>% filter(!is.na(MEASUREMENT))

# POINT 3: Set negative values to 0
# We cannot really measure negative fluorescence values - this is unrealistic.
# All_plates_data <- All_plates_data %>%
  # mutate(Plate = case_when(is.na(Plate) ~ 0, TRUE ~ Plate), # ensure that Dose Response Experiments are marked as Plate = 0
         # MEASUREMENT      = case_when(MEASUREMENT < 0 ~ 0, TRUE ~ MEASUREMENT),
         # Concentration = case_when(Concentration < 0 ~ 0, TRUE ~ Concentration),
         # Concentration_DILUTION_FACTOR = case_when(Concentration_DILUTION_FACTOR < 0 ~ 0, TRUE ~ Concentration_DILUTION_FACTOR))

# Adjust the column types as needed
# we want to turn stimulation CONDITION and stimulation days into factors for easier handling downstream
All_plates_data$CONDITION <- as.factor(All_plates_data$CONDITION)
All_plates_data$STIM_DAY  <- as.factor(All_plates_data$STIM_DAY)

color_palette_key <- setNames(All_plates_data$PLOTTING_COLOR, All_plates_data$CELL_LINE)
color_palette_key <- unique(color_palette_key) # Remove duplicates, if any

################################################################################################################################################################
################################################################################################################################################################
################################################################################################################################################################

# Plot for different cohorts & respective positive/negative controls
plot_by_cohorts <- plot_ELISA(FILTER_VALUES = c("MyD88-T6BD",
                                                "BDLD_57",
                                                "BDLD_50",
                                                "BDLD_67",
                                                "BDLD_69",
                                                "BDLD_6-",
                                                "BDLD_62"), 
                              FILTER_TYPE = "COHORT", 
                              POSITIVE_CTRL = c("3E10_GFP", "MyD88_GFP"), 
                              NEGATIVE_CTRL = c("204_TRIPLE_KO", "tKO_EL4"))

plot_by_cohorts[1]
COMBINED_DATA <- as.data.frame(plot_by_cohorts[2])
MEANS         <- as.data.frame(plot_by_cohorts[3])
MOM_SUBSET    <- as.data.frame(plot_by_cohorts[4])
# x_label = ""
# y_label = "relative IL-2 conc."
# plot_title = "IL-2 ELISA"
# 
# COLOR = "#047869"
# COLOR = "#f8ba00"
# COLOR = "#24414e"
# COLOR = "#ff968d"
# SEED = 600
# 
# ggplot(MEANS, aes(x = CL_NAME_ON_PLOT)) +
#   geom_col(     data = MOM_SUBSET,  aes(y = triplicate_mean_per_day, fill = CONDITION), position = position_dodge(width = 1), alpha = 0.5) +
#   geom_point(   data = MEANS,       aes(y = triplicate_mean_per_day, group = CONDITION, shape = STIM_DAY),               position = position_jitterdodge(jitter.height = 0, jitter.width = 1.2, seed = SEED), col = "white", size = 4) +
#   geom_point(   data = MEANS,       aes(y = triplicate_mean_per_day, group = CONDITION, shape = STIM_DAY), position = position_jitterdodge(jitter.height = 0, jitter.width = 1.2, seed = SEED), 
#                 col = "black",
#                 size = 3) +
#   geom_errorbar(data = MOM_SUBSET, aes(ymin = triplicate_mean_per_day - triplicate_sd_per_day, 
#                                        ymax = triplicate_mean_per_day + triplicate_sd_per_day, group = CONDITION), width = 0.25, position = position_dodge(width = 1)) +
#   labs(x = x_label,
#        y = y_label) +
#   scale_fill_manual(values = c("UNSTIM" = "gray50", "STIM" = COLOR)) +
#   ggtitle(plot_title) +
#   theme_cowplot() +
#   theme(legend.position = "bottom") +
#   theme(plot.title = element_text(hjust = 0.5)) +
#   coord_flip()

# save_plots(folder_name = "BDLD_57_BDLD_6", plots = list(plot_by_cohorts[[1]]))
save_plots(folder_name = "BDLD_57", plots = list(plot_by_cohorts[[1]]))

# Plot for a specific day
plot_by_day <- plot_ELISA(FILTER_VALUES = c("2023-06-21"), FILTER_TYPE = "DAY", POSITIVE_CTRL = c("3E10_GFP", "MyD88_GFP"), NEGATIVE_CTRL = c("204_TRIPLE_KO", "tKO_EL4"), plot_faceted_by_date = T)
save_plots(folder_name = "20230621", plots = list(plot_by_day[[1]]))

################################################################################################################################################################
################################################################################################################################################################
################################################################################################################################################################

plot_dr_by_day <- plot_dose_response_ELISA(DATA = All_plates_data, FILTER_VALUES = c("2022-12-08"),
                                           # x_label = "IL-1 [ng/uL]", y_label = "relative IL-2 secretion", plot_title = "Dose Response IL-2 ELISA", subtitle = subtitle
                                           )
list(plot_dr_by_day[[1]])
save_plots(folder_name = "DR_20221208", plots = list(plot_dr_by_day[[1]]))

plot_dr_by_day <- plot_dose_response_ELISA(DATA = All_plates_data, FILTER_VALUES = c("2022-11-24"))
list(plot_dr_by_day[[1]])
save_plots(folder_name = "DR_20221124", plots = list(plot_dr_by_day[[1]]))

plot_dr_by_day <- plot_dose_response_ELISA(DATA = All_plates_data, FILTER_VALUES = c("2022-10-06"))
list(plot_dr_by_day[[1]])
save_plots(folder_name = "DR_20221006", plots = list(plot_dr_by_day[[1]]))

################################################################################################################################################################
################################################################################################################################################################
################################################################################################################################################################

# Elke TNFa ELISA 
plot_dr_by_day2 <- plot_dose_response_ELISA_2(FILTER_VALUES = c("2023-11-16"), x_label = "", y_label = "relative TNFa secretion", plot_title = "TNF-alpha secretion of mMPh wt vs. MyD88/IRAK4 dKO")
save_plots(folder_name = "20231116", plots = list(plot_dr_by_day2$DR2_PLOT_1, 
                                                  plot_dr_by_day2$DR2_PLOT_2, 
                                                  plot_dr_by_day2$DR2_PLOT_3, 
                                                  plot_dr_by_day2$DR2_PLOT_4))

# ELISA IL-6 ELISA
plot_dr_by_day2 <- plot_dose_response_ELISA_2(FILTER_VALUES = c("2023-11-21"), x_label = "", y_label = "relative IL-6 secretion", plot_title = "IL-6 secretion of mMPh wt vs. MyD88/IRAK4 dKO")
save_plots(folder_name = "20231121", plots = list(plot_dr_by_day2$DR2_PLOT_1, 
                                                  plot_dr_by_day2$DR2_PLOT_2, 
                                                  plot_dr_by_day2$DR2_PLOT_3, 
                                                  plot_dr_by_day2$DR2_PLOT_4))

plot_dr_by_day2 <- plot_dose_response_ELISA_2(FILTER_VALUES = c("2023-11-23"), x_label = "", y_label = "relative IL-6 secretion", plot_title = "IL-6 secretion of mMPh wt vs. MyD88/IRAK4 dKO")
save_plots(folder_name = "20231123", plots = list(plot_dr_by_day2$DR2_PLOT_1, 
                                                  plot_dr_by_day2$DR2_PLOT_2, 
                                                  plot_dr_by_day2$DR2_PLOT_3, 
                                                  plot_dr_by_day2$DR2_PLOT_4))
